// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atjezuvbnamkpsxdjyub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0amV6dXZibmFta3BzeGRqeXViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MzIwMjMsImV4cCI6MjA2MDUwODAyM30.eNiutMDA4NQJ0Uu1P5fnmNnfW-ChAXI0ESV8JaDZPD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);